  List<String> chromeHistory = [
    "Where is the Tower of Giza?",
    "What are the steps to bake chocolate chip cookies?",
    "How do you create a website? Can you provide a tutorial?",
    "What are the top travel destinations for summer?",
    "What are the symptoms of a common cold?",
    "Where can I find reviews for a new restaurant in town?",
    "What are the latest news updates?",
    "Where can I find DIY home improvement ideas?",
    "Can you suggest a blog on mindfulness meditation techniques?",
    "How do you tie a tie?",
    "Where can I find a YouTube video on beginner guitar chords?",
    "What are some time management tips?",
    "What's the weather forecast for the weekend?",
    "Where can I find information about the Tower of Giza?",
    "How do you solve a Rubik's cube?",
    "What are the lyrics to a popular song?",
    "Can you recommend some new book releases?",
    "What are the latest fashion trends?",
    "Where can I find job interview tips?",
    "Where can I learn about ancient Egyptian architecture?",
    "How do you say 'hello' in French?",
    "What are the best ways to learn a new language?",
    "Where can I find healthy recipes?",
    "How do you meditate?",
    "Where can I buy affordable furniture online?",
    "Where can I find information about the Great Wall of China?",
    "What are some tips for improving concentration?",
    "How do you cook pasta al dente?",
    "Where can I find reviews for the latest movies?",
    "How do you play chess?",
    "What are some popular hiking trails?",
    "Where can I learn about the history of jazz music?",
    "How do you calculate the area of a circle?",
    "Where can I find information about the Mona Lisa?",
    "What are some indoor activities for kids?",
    "Where can I find budget-friendly vacation destinations?",
    "How do you perform CPR?",
    "Where can I find reviews for home appliances?",
    "What are some effective study techniques?",
    "Where can I find information about the Eiffel Tower?",
    "How do you make a paper airplane?",
    "What are some beginner-friendly knitting patterns?",
    "Where can I find advice on personal finance management?",
    "How do you start a blog?",
    "What are some ways to reduce stress?",
    "Where can I find reviews for smartphones?",
    "How do you make sushi at home?",
    "What are some tips for improving memory?",
    "Where can I find information about famous painters?",
    "How do you solve a Sudoku puzzle?",
    "What are some benefits of regular exercise?",
    "Where can I find reviews for laptops?",
    "How do you change a flat tire?",
    "What are some ways to boost creativity?",
    "Where can I find information about the Taj Mahal?",
    "How do you make a resume?",
    "What are some tips for public speaking?",
    "Where can I find reviews for digital cameras?",
    "How do you play the guitar?",
    "What are some healthy snack ideas?",
    "Where can I find information about Mount Everest?",
    "How do you brew the perfect cup of coffee?",
    "What are some tips for better sleep?",
    "Where can I find reviews for tablets?",
    "How do you start a small business?",
    "What are some effective ways to save money?",
    "Where can I find information about space exploration?",
    "How do you make a grilled cheese sandwich?",
    "What are some tips for better time management?",
    "Where can I find reviews for headphones?",
    "How do you perform a basic first aid?",
    "What are some popular tourist attractions in Paris?",
    "Where can I learn about the history of photography?",
    "How do you start a podcast?",
    "What are some tips for organizing your closet?",
    "Where can I find reviews for gaming consoles?",
    "How do you make homemade ice cream?",
    "What are some ways to improve communication skills?",
    "Where can I find information about the Amazon rainforest?",
    "How do you start a YouTube channel?",
    "What are some tips for traveling solo?",
    "Where can I find reviews for e-readers?",
    "How do you make a classic margarita?",
    "What are some tips for effective studying?",
    "Where can I learn about the history of ancient Rome?",
    "How do you start a fitness routine?",
    "What are some healthy breakfast ideas?",
    "Where can I find reviews for running shoes?",
    "How do you make a paper crane?",
    "What are some tips for building self-confidence?",
    "Where can I find information about the Statue of Liberty?",
    "How do you start a vegetable garden?",
    "What are some tips for healthy eating?",
    "Where can I find reviews for baby products?",
    "How do you make a classic martini?",
    "What are some tips for staying motivated?",
    "Where can I find information about the pyramids of Egypt?",
    "How do you start a book club?",
    "What are some tips for improving posture?",
    "Where can I find reviews for travel luggage?",
    "How do you make a smoothie?",
    "What are some tips for successful job interviews?",
  ];
